services:
  pokedex-api:
    image: pokedex-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - POKEMON_API_URL=http://pokeapi:8080
      - TRANSLATION_API_URL=http://funtranslations-api:8080
    depends_on:
      - pokeapi
      - funtranslations-api

  pokeapi:
    image: wiremock/wiremock:3.3.1
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/pokeapi:/home/wiremock

  funtranslations-api:
    image: wiremock/wiremock:3.3.1
    ports:
      - "8082:8080"
    volumes:
      - ./wiremock/funtranslations:/home/wiremock
